{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example",
    "module": "UberProject-EntityService",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "UberProject-EntityService-0.0.1-SNAPSHOT-plain.jar",
          "url": "UberProject-EntityService-0.0.1-SNAPSHOT-plain.jar",
          "size": 13901,
          "sha512": "468a3d8f613c3cf61ef7ea15428adf63741bd428635d2f5e95d3a93aff8fc0a456cf435da34aab56dc63a3ac7af0f3c2511e61836f1ed9c85234895d883be50d",
          "sha256": "68264fff500738b5da83fb1e816006028b4c5bdca8cb39d81427a919aa67acdd",
          "sha1": "efb452fd48518b8f022ecc204f9a2f113139154c",
          "md5": "622527568f05f769a5a5561adb6ecb92"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-flyway"
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-mysql"
        },
        {
          "group": "org.mariadb.jdbc",
          "module": "mariadb-java-client"
        }
      ],
      "files": [
        {
          "name": "UberProject-EntityService-0.0.1-SNAPSHOT-plain.jar",
          "url": "UberProject-EntityService-0.0.1-SNAPSHOT-plain.jar",
          "size": 13901,
          "sha512": "468a3d8f613c3cf61ef7ea15428adf63741bd428635d2f5e95d3a93aff8fc0a456cf435da34aab56dc63a3ac7af0f3c2511e61836f1ed9c85234895d883be50d",
          "sha256": "68264fff500738b5da83fb1e816006028b4c5bdca8cb39d81427a919aa67acdd",
          "sha1": "efb452fd48518b8f022ecc204f9a2f113139154c",
          "md5": "622527568f05f769a5a5561adb6ecb92"
        }
      ]
    }
  ]
}
