spring.application.name=UberProject-EntityService
spring.datasource.url=jdbc:mariadb://localhost:3306/Uber_Db_Local


spring.datasource.username=luffy

spring.datasource.password=Plmoknijb@123
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

server.port=6969
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.url=jdbc:mariadb://localhost:3306/Uber_Db_Local
spring.flyway.user=luffy
spring.flyway.password=Plmoknijb@123
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
